apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pihole-unbound
    io.containers.autoupdate: registry
  name: pihole-unbound
spec:
  shareProcessNamespace: false
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  containers:
    - name: valkey
      command:
      - valkey-server
      - /usr/local/etc/valkey/valkey.conf
      image: docker.io/valkey/valkey:alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
          - mountPath: /data:z
            name: valkey-data
          - mountPath: /usr/local/etc/valkey/valkey.conf:z
            name: valkey-conf
            readonly: true
          - mountPath: /var/run/redis/
            name: valkey-run
    - name: unbound
      args:
      - 'sh'
      - '-c'
      - "curl -o /etc/unbound/root.hints https://www.internic.net/domain/named.root && sh /entrypoint.sh"
      image: ghcr.io/crazy-max/unbound:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
          - mountPath: /var/log/unbound/:z
            name: unbound-log
          - mountPath: /etc/unbound/unbound.conf:z
            name: unbound-conf
            readOnly: true
          - mountPath: /etc/unbound/unbound_server.key:z
            name: unbound-server-key
            readOnly: true
          - mountPath: /etc/unbound/unbound_server.pem:z
            name: unbound-server-pem
            readOnly: true
          - mountPath: /etc/unbound/unbound_control.key:z
            name: unbound-control-key
            readOnly: true
          - mountPath: /etc/unbound/unbound_control.pem:z
            name: unbound-control-pem
            readOnly: true
          - mountPath: /etc/unbound/root.hints:z
            name: unbound-roothints
          - mountPath: /var/run/redis
            name: valkey-run
            readOnly: true
      securityContext:
       capabilities:
         add: ["NET_ADMIN", "NET_RAW"]
    - name: pihole
      # image: ghcr.io/pi-hole/pihole:latest
      image: docker.io/jacklul/pihole:latest
      imagePullPolicy: IfNotPresent
      env:
      - name: CUSTOM_CACHE_SIZE # ignored by DNSSEC
        value: "0"
      - name: DNS_BOGUS_PRIV
        value: "true"
      - name: DNS_FQDN_REQUIRED
        value: "true"
      - name: PIHOLE_DNS_
        value: "::1#5053;127.0.0.1#5053"
        #;127.0.0.1#5053
      - name: REV_SERVER
        value: "true"
      - name: REV_SERVER_CIDR
        value: ""
      - name: REV_SERVER_DOMAIN
        value: ""
      - name: REV_SERVER_TARGET
        value: ""
      - name: TZ
        value: "Europe/Brussels"
      - name: WEBPASSWORD
        value: GENERATEPASSWORDHERE
      - name: WEBTHEME
        value: "default-darker"
      - name: FTLCONF_LOCAL_IPV4
        value: ""
      - name: FTLCONF_LOCAL_IPV6
        value: ""
      - name: DNSMASQ_LISTENING
        value: "all"
      - name: DNSSEC
        value: "false"
      - name: FTLCONF_DEBUG_CLIENTS
        value: "true"
      - name: FTLCONF_EDNS0_ECS
        value: "false"
      - name: UPDATE_GRAVITY
        value: "false"
      - name: ADLISTS_URL
        value: "https://v.firebog.net/hosts/lists.php?type=tick"
      - name: WHITELIST_URL
        value: "https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"
      - name: REGEX_BLACKLIST_URL
        value: "https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"
      volumeMounts:
          - mountPath: /etc/dnsmasq.d:z
            name: pihole-dnsmasq
          - mountPath: /etc/pihole:z
            name: pihole-root
      securityContext:
       capabilities:
         add: ["NET_ADMIN", "NET_RAW", "SYS_ADMIN", "SYS_NICE", "CHOWN", "NET_BIND_SERVICE"]
  volumes:
  - hostPath:
      path: /pihole/dnsmasq
      type: Directory
    name: pihole-dnsmasq
  - hostPath:
      path: /pihole/config
      type: Directory
    name: pihole-root
  - hostPath:
      path: /unbound/log
      type: Directory
    name: unbound-log
  - hostPath:
      path: /unbound/config/unbound.conf
      type: File
    name: unbound-conf
  - hostPath:
      path: /unbound/unbound_server.key
      type: File
    name: unbound-server-key
  - hostPath:
      path: /unbound/unbound_server.pem
      type: File
    name: unbound-server-pem
  - hostPath:
      path: /unbound/unbound_control.key
      type: File
    name: unbound-control-key
  - hostPath:
      path: /unbound/unbound_control.pem
      type: File
    name: unbound-control-pem
  - hostPath:
      path: /unbound/root.hints
      type: File
    name: unbound-roothints
  - hostPath:
      path: /valkey
      type: Directory
    name: valkey-data
  - hostPath:
      path: /valkey/valkey.conf
      type: Directory
    name: valkey-conf
  - hostPath:
      path: /valkey/run
      type: Directory
    name: valkey-run
status: {}
